### ISSUE TITLE
Package breaks extension manager in Pimcore 6.3.5

### ISSUE THREAD

**Issue by shaselboeck** [dachcom-digital/pimcore-members#128] opened 2019-12-10 13:47 UTC
Get the following error after installing / activating the package.

`Timestamp: Tue Dec 10 2019 14:32:35 GMT+0100 (Mitteleuropäische Normalzeit)
Status: 500 | 
URL: /admin/extensionmanager/admin/extensions?_dc=1575984753364
Method: GET
Message: Argument 1 passed to MembersBundle\Document\Builder\BrickBuilder::__construct() must be an instance of Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage, instance of Symfony\Component\Security\Core\Authentication\Token\Storage\UsageTrackingTokenStorage given, called in /srv/www/pimcoretest.dev.m-s.de/htdocs/var/cache/prod/Container5k6xF8j/getMembers_Area_Brick_LoginService.php on line 18`

**Comment by AndiKeiser** [comment] 2019-12-17 08:12
Duplicate of #127

**Comment by solverat** [comment] 2020-02-21 13:47
As @AndiKeiser mentioned, see #127.

**Closed by solverat** 2020-02-21 13:47 UTC
